# Generated by Django 4.0.6 on 2022-08-08 04:35

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2001-02-01', validators=[users.validators.check_age_validator]),
            preserve_default=False,
        ),
    ]
